### ISSUE TITLE
Missing dep Mac::Pasteboard prereq on darwin

### ISSUE THREAD

**Issue by plicease** [shlomif/Clipboard#1]
```
nyx$ ./Build test
t/drivers.t .. Can't locate Mac/Pasteboard.pm in @INC (@INC contains: lib ./t/lib /Users/gollis/.cpanm/work/1550621676.58371/Clipboard-0.19/blib/lib /Users/gollis/.cpanm/work/1550621676.58371/Clipboard-0.19/blib/arch /Users/gollis/.plenv/versions/5.14.2/lib/perl5/site_perl/5.14.2/darwin-thread-multi-2level /Users/gollis/.plenv/versions/5.14.2/lib/perl5/site_perl/5.14.2 /Users/gollis/.plenv/versions/5.14.2/lib/perl5/5.14.2/darwin-thread-multi-2level /Users/gollis/.plenv/versions/5.14.2/lib/perl5/5.14.2 .) at lib/Clipboard/MacPasteboard.pm line 6.
BEGIN failed--compilation aborted at lib/Clipboard/MacPasteboard.pm line 6.
Compilation failed in require at lib/Clipboard.pm line 39.
BEGIN failed--compilation aborted at t/lib/Test/Clipboard.pm line 6.
Compilation failed in require at t/drivers.t line 5.
BEGIN failed--compilation aborted at t/drivers.t line 5.
t/drivers.t .. skipped: (no reason given)
t/mock.t ..... Can't locate Mac/Pasteboard.pm in @INC (@INC contains: lib ./t/lib /Users/gollis/.cpanm/work/1550621676.58371/Clipboard-0.19/blib/lib /Users/gollis/.cpanm/work/1550621676.58371/Clipboard-0.19/blib/arch /Users/gollis/.plenv/versions/5.14.2/lib/perl5/site_perl/5.14.2/darwin-thread-multi-2level /Users/gollis/.plenv/versions/5.14.2/lib/perl5/site_perl/5.14.2 /Users/gollis/.plenv/versions/5.14.2/lib/perl5/5.14.2/darwin-thread-multi-2level /Users/gollis/.plenv/versions/5.14.2/lib/perl5/5.14.2 .) at lib/Clipboard/MacPasteboard.pm line 6.
BEGIN failed--compilation aborted at lib/Clipboard/MacPasteboard.pm line 6.
Compilation failed in require at lib/Clipboard.pm line 39.
BEGIN failed--compilation aborted at t/lib/Test/Clipboard.pm line 6.
Compilation failed in require at t/mock.t line 5.
BEGIN failed--compilation aborted at t/mock.t line 5.
t/mock.t ..... skipped: (no reason given)

Test Summary Report
-------------------
t/drivers.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
t/mock.t   (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
Files=2, Tests=0,  0 wallclock secs ( 0.01 usr  0.01 sys +  0.09 cusr  0.02 csys =  0.13 CPU)
Result: FAIL
Failed 2/2 test programs. 0/0 subtests failed.
```

tests passed and installed after manually installing `Mac::Pasteboard`.

**Comment by shlomif** [comment]
On Tue, 19 Feb 2019 16:18:39 -0800
Graham✈️✈️ <notifications@github.com> wrote:

> ```
> nyx$ ./Build test
> t/drivers.t .. Can't locate Mac/Pasteboard.pm in @INC (@INC contains:
> lib ./t/lib /Users/gollis/.cpanm/work/1550621676.58371/Clipboard-0.19/blib/lib /Users/gollis/.cpanm/work/1550621676.58371/Clipboard-0.19/blib/arch /Users/gollis/.plenv/versions/5.14.2/lib/perl5/site_perl/5.14.2/darwin-thread-multi-2level /Users/gollis/.plenv/versions/5.14.2/lib/perl5/site_perl/5.14.2 /Users/gollis/.plenv/versions/5.14.2/lib/perl5/5.14.2/darwin-thread-multi-2level /Users/gollis/.plenv/versions/5.14.2/lib/perl5/5.14.2 .)
> at lib/Clipboard/MacPasteboard.pm line 6. BEGIN failed--compilation aborted
> at lib/Clipboard/MacPasteboard.pm line 6. Compilation failed in require at
> lib/Clipboard.pm line 39. BEGIN failed--compilation aborted at
> t/lib/Test/Clipboard.pm line 6. Compilation failed in require at t/drivers.t
> line 5. BEGIN failed--compilation aborted at t/drivers.t line 5.
> t/drivers.t .. skipped: (no reason given) t/mock.t ..... Can't locate
> Mac/Pasteboard.pm in @INC (@INC contains:
> lib ./t/lib /Users/gollis/.cpanm/work/1550621676.58371/Clipboard-0.19/blib/lib /Users/gollis/.cpanm/work/1550621676.58371/Clipboard-0.19/blib/arch /Users/gollis/.plenv/versions/5.14.2/lib/perl5/site_perl/5.14.2/darwin-thread-multi-2level /Users/gollis/.plenv/versions/5.14.2/lib/perl5/site_perl/5.14.2 /Users/gollis/.plenv/versions/5.14.2/lib/perl5/5.14.2/darwin-thread-multi-2level /Users/gollis/.plenv/versions/5.14.2/lib/perl5/5.14.2 .)
> at lib/Clipboard/MacPasteboard.pm line 6. BEGIN failed--compilation aborted
> at lib/Clipboard/MacPasteboard.pm line 6. Compilation failed in require at
> lib/Clipboard.pm line 39. BEGIN failed--compilation aborted at
> t/lib/Test/Clipboard.pm line 6. Compilation failed in require at t/mock.t
> line 5. BEGIN failed--compilation aborted at t/mock.t line 5. t/mock.t .....
> skipped: (no reason given)
> 
> Test Summary Report
> -------------------
> t/drivers.t (Wstat: 512 Tests: 0 Failed: 0)
>   Non-zero exit status: 2
> t/mock.t   (Wstat: 512 Tests: 0 Failed: 0)
>   Non-zero exit status: 2
> Files=2, Tests=0,  0 wallclock secs ( 0.01 usr  0.01 sys +  0.09 cusr  0.02
> csys =  0.13 CPU) Result: FAIL
> Failed 2/2 test programs. 0/0 subtests failed.
> ```
> 
> tests passed and installed after manually installing `Mac::Pasteboard`.
> 

Thanks for the report.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Beginners Site for the Vim text editor - http://vim.begin-site.org/

If you have the same ideas as everybody else, but have them one week earlier
than everyone else — then you will be hailed as a visionary. But if you have
them five years earlier, you will be named a lunatic. ( Barry Jones )

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@plicease : is it fixed in Clipboard-0.21?

**Comment by shlomif** [comment]
Closing for now to avoid clutter . If the issue persists then I can reopen. Thanks!

**Comment by sshaw** [comment]
Still seeing this using 0.22:

```
Fetching with LWP:
http://www.cpan.org/authors/id/S/SH/SHLOMIF/CHECKSUMS
Checksum for /Users/sshaw/.cpan/sources/authors/id/S/SH/SHLOMIF/Clipboard-0.22.tar.gz ok

  CPAN.pm: Building S/SH/SHLOMIF/Clipboard-0.22.tar.gz

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Clipboard' version '0.22'
Building Clipboard
  SHLOMIF/Clipboard-0.22.tar.gz
  ./Build -- OK
'YAML' not installed, will not store persistent state
Running Build test
t/drivers.t .. Can't locate Mac/Pasteboard.pm in @INC (you may need to install the Mac::Pasteboard module) (@INC contains: lib ./t/lib /Users/sshaw/.cpan/build/Clipboard-0.22-r3aHpH/blib/lib /Users/sshaw/.cpan/build/Clipboard-0.22-r3aHpH/blib/arch /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at lib/Clipboard/MacPasteboard.pm line 6.
BEGIN failed--compilation aborted at lib/Clipboard/MacPasteboard.pm line 6.
Compilation failed in require at lib/Clipboard.pm line 56.
BEGIN failed--compilation aborted at t/lib/Test/Clipboard.pm line 6.
Compilation failed in require at t/drivers.t line 5.
BEGIN failed--compilation aborted at t/drivers.t line 5.
# Looks like your test exited with 2 before it could output anything.
t/drivers.t .. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
t/mock.t ..... Can't locate Mac/Pasteboard.pm in @INC (you may need to install the Mac::Pasteboard module) (@INC contains: lib ./t/lib /Users/sshaw/.cpan/build/Clipboard-0.22-r3aHpH/blib/lib /Users/sshaw/.cpan/build/Clipboard-0.22-r3aHpH/blib/arch /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at lib/Clipboard/MacPasteboard.pm line 6.
BEGIN failed--compilation aborted at lib/Clipboard/MacPasteboard.pm line 6.
Compilation failed in require at lib/Clipboard.pm line 56.
BEGIN failed--compilation aborted at t/lib/Test/Clipboard.pm line 6.
Compilation failed in require at t/mock.t line 5.
BEGIN failed--compilation aborted at t/mock.t line 5.
# Looks like your test exited with 2 before it could output anything.
t/mock.t ..... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run

Test Summary Report
-------------------
t/drivers.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/mock.t   (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=2, Tests=0,  0 wallclock secs ( 0.01 usr  0.02 sys +  0.03 cusr  0.01 csys =  0.07 CPU)
Result: FAIL
Failed 2/2 test programs. 0/0 subtests failed.
  SHLOMIF/Clipboard-0.22.tar.gz
  ./Build test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports SHLOMIF/Clipboard-0.22.tar.gz
Running Build install
  make test had returned bad status, won't install without force
```
OS:

```
~/code >sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

I also had this problem on an older Mac (10.12, maybe, I can check if necessary).

**Comment by sshaw** [comment]
This was for Perl 5.18 but also fails for 5.31.8

**Comment by shlomif** [comment]
@sshaw : please try again in 0.23 . Reopening for now.

**Comment by sshaw** [comment]
```
~/code/perl/oaf >cpanm  Clipboard
--> Working on Clipboard
Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/Clipboard-0.23.tar.gz ... OK
Configuring Clipboard-0.23 ... OK
Building and testing Clipboard-0.23 ... FAIL
! Installing Clipboard failed. See /Users/sshaw/.cpanm/work/1583537805.9900/build.log for details. Retry with --force to force install it.
~/code/perl/oaf >tail /Users/sshaw/.cpanm/work/1583537805.9900/build.log
t/drivers.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/mock.t   (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=2, Tests=0,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.04 cusr  0.01 csys =  0.08 CPU)
Result: FAIL
Failed 2/2 test programs. 0/0 subtests failed.
-> FAIL Installing Clipboard failed. See /Users/sshaw/.cpanm/work/1583537805.9900/build.log for details. Retry with --force to force install it.
```

---
```
~/code/perl/oaf >tail -40 /Users/sshaw/.cpanm/work/1583537805.9900/build.log
Checking if you have strict 0 ... Yes (1.11)
Checking if you have CGI 0 ... Yes (4.46)
Checking if you have warnings 0 ... Yes (1.37)
Checking if you have File::Spec 0 ... Yes (4.74)
Checking if you have lib 0 ... Yes (0.64)
Building and testing Clipboard-0.23
Building Clipboard
Can't locate Mac/Pasteboard.pm in @INC (you may need to install the Mac::Pasteboard module) (@INC contains: lib ./t/lib /Users/sshaw/.cpanm/work/1583537805.9900/Clipboard-0.23/blib/lib /Users/sshaw/.cpanm/work/1583537805.9900/Clipboard-0.23/blib/arch /Users/sshaw/perl5/perlbrew/perls/cperl-5.26.5/lib/site_cperl/5.26.5/darwin-2level /Users/sshaw/perl5/perlbrew/perls/cperl-5.26.5/lib/site_cperl/5.26.5 /Users/sshaw/perl5/perlbrew/perls/cperl-5.26.5/lib/5.26.5/darwin-2level /Users/sshaw/perl5/perlbrew/perls/cperl-5.26.5/lib/5.26.5 .) at lib/Clipboard/MacPasteboard.pm line 6.
BEGIN failed--compilation aborted at lib/Clipboard/MacPasteboard.pm line 6.
Compilation failed in require at lib/Clipboard.pm line 56.
BEGIN failed--compilation aborted at t/lib/Test/Clipboard.pm line 6.
Compilation failed in require at t/drivers.t line 5.
BEGIN failed--compilation aborted at t/drivers.t line 5.
# Looks like your test exited with 2 before it could output anything.
t/drivers.t ..
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
Can't locate Mac/Pasteboard.pm in @INC (you may need to install the Mac::Pasteboard module) (@INC contains: lib ./t/lib /Users/sshaw/.cpanm/work/1583537805.9900/Clipboard-0.23/blib/lib /Users/sshaw/.cpanm/work/1583537805.9900/Clipboard-0.23/blib/arch /Users/sshaw/perl5/perlbrew/perls/cperl-5.26.5/lib/site_cperl/5.26.5/darwin-2level /Users/sshaw/perl5/perlbrew/perls/cperl-5.26.5/lib/site_cperl/5.26.5 /Users/sshaw/perl5/perlbrew/perls/cperl-5.26.5/lib/5.26.5/darwin-2level /Users/sshaw/perl5/perlbrew/perls/cperl-5.26.5/lib/5.26.5 .) at lib/Clipboard/MacPasteboard.pm line 6.
BEGIN failed--compilation aborted at lib/Clipboard/MacPasteboard.pm line 6.
Compilation failed in require at lib/Clipboard.pm line 56.
BEGIN failed--compilation aborted at t/lib/Test/Clipboard.pm line 6.
Compilation failed in require at t/mock.t line 5.
BEGIN failed--compilation aborted at t/mock.t line 5.
# Looks like your test exited with 2 before it could output anything.
t/mock.t .....
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run

Test Summary Report
-------------------
t/drivers.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/mock.t   (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=2, Tests=0,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.04 cusr  0.01 csys =  0.08 CPU)
Result: FAIL
Failed 2/2 test programs. 0/0 subtests failed.
-> FAIL Installing Clipboard failed. See /Users/sshaw/.cpanm/work/1583537805.9900/build.log for details. Retry with --force to force install it.
```
---
```
~/code/perl/oaf >sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

😿

**Comment by shlomif** [comment]
Hi @sshaw ! Thanks for the report - please try again with v0.24. Thanks!

**Comment by sshaw** [comment]
Ok, progress. Now a problem with `Mac::Pasteboard`. C bindings. Seems like it'd be better to shell-out to system command but, maybe I'm missing something. 

Error:
```
cpanm (App::cpanminus) 1.7042 on perl 5.026005 built for darwin-2level
Work directory is /Users/sshaw/.cpanm/work/1583570824.14768
You have make /usr/bin/make
You have /usr/local/bin/wget
You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
You have /usr/bin/unzip
--> Working on http://www.cpan.org/authors/id/S/SH/SHLOMIF/Clipboard-0.24.tar.gz
Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/Clipboard-0.24.tar.gz
-> OK
Unpacking Clipboard-0.24.tar.gz
Entering Clipboard-0.24
Checking configure dependencies from META.json
Checking if you have Module::Build 0.38 ... Yes (0.4231)
Checking if you have ExtUtils::Install 1.46 ... Yes (2.14)
Configuring Clipboard-0.24
Running Build.PL
Checking prerequisites...
  requires:
    !  Mac::Pasteboard is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Clipboard' version '0.24'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Test::More 0.88 ... Yes (1.401015)
Checking if you have CGI 0 ... Yes (4.46)
Checking if you have warnings 0 ... Yes (1.37)
Checking if you have strict 0 ... Yes (1.11)
Checking if you have File::Spec 0 ... Yes (4.74)
Checking if you have Mac::Pasteboard 0.011 ... No
Checking if you have File::Temp 0 ... Yes (0.2308)
Checking if you have IPC::Open2 0 ... Yes (1.04)
Checking if you have Module::Build 0.28 ... Yes (0.4231)
Checking if you have lib 0 ... Yes (0.64)
Checking if you have URI::Escape 0 ... Yes (3.31)
==> Found dependencies: Mac::Pasteboard
Searching Mac::Pasteboard (0.011) on cpanmetadb ...
--> Working on Mac::Pasteboard
Fetching http://www.cpan.org/authors/id/W/WY/WYANT/Mac-Pasteboard-0.011.tar.gz
-> OK
Unpacking Mac-Pasteboard-0.011.tar.gz
Entering Mac-Pasteboard-0.011
Checking configure dependencies from META.json
Checking if you have Module::Build 0.38 ... Yes (0.4231)
Checking if you have ExtUtils::Install 1.46 ... Yes (2.14)
Configuring Mac-Pasteboard-0.011
Running Build.PL

<<<< NOTICE >>>>

As of version 0.007_01, the pbtool script is installed by default, and the
prompt for whether or not to install it is removed. If you do not want
it installed, run this script with the -n option. The -y option will
remain for compatability.

The pbtool script is installed by default. If you do not want this,
rerun this script specifying -n.
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Mac-Pasteboard' version '0.011'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Test::More 0.96 ... Yes (1.401015)
Checking if you have Scalar::Util 1.01 ... Yes (1.50_11)
Checking if you have Carp 0 ... Yes (1.42)
Checking if you have warnings 0 ... Yes (1.37)
Checking if you have strict 0 ... Yes (1.11)
Checking if you have Encode 0 ... Yes (2.98)
Checking if you have ExtUtils::CBuilder 0 ... Yes (0.280230)
Building and testing Mac-Pasteboard-0.011
Building Mac-Pasteboard
Pasteboard.xs -> lib/Mac/Pasteboard.xs
constant-c.inc -> lib/Mac/constant-c.inc
constant-h.inc -> lib/Mac/constant-h.inc
constant-xs.inc -> lib/Mac/constant-xs.inc
pbl.c -> lib/Mac/pbl.c
pbl.h -> lib/Mac/pbl.h
ppport.h -> lib/Mac/ppport.h
cc -Ilib/Mac -I/Users/sshaw/perl5/perlbrew/perls/cperl-5.26.5/lib/5.26.5/darwin-2level/CORE -DTIGER -DUSE_MACTYPES -c -fno-common -DPERL_DARWIN -mmacosx-version-min=10.9 -fno-strict-aliasing -pipe -fstack-protector -DPERL_USE_SAFE_PUTENV -O3 -o lib/Mac/pbl.o lib/Mac/pbl.c
In file included from lib/Mac/pbl.c:40:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:27:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Headers/ATS.h:28:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Headers/ATSLayoutTypes.h:28:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Headers/ATSTypes.h:24:
In file included from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGGeometry.h:8:
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:282:78: error: 'swift_name' attribute cannot be applied to this declaration
typedef struct  CF_BRIDGED_TYPE(id) __IOSurface *IOSurfaceRef __attribute__((swift_name("IOSurfaceRef")));
                                                                             ^
1 error generated.
error building lib/Mac/pbl.o from 'lib/Mac/pbl.c' at /Users/sshaw/perl5/perlbrew/perls/cperl-5.26.5/lib/5.26.5/ExtUtils/CBuilder/Base.pm line 185.
-> FAIL Installing Mac::Pasteboard failed. See /Users/sshaw/.cpanm/work/1583570824.14768/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'Mac::Pasteboard' is not installed
-> FAIL Bailing out the installation for Clipboard-0.24.
```

**Comment by shlomif** [comment]
@sshaw : Thanks for the report! Please report the new issue at https://metacpan.org/release/Mac-Pasteboard .

**Comment by shlomif** [comment]
@sshaw @plicease : hi! Can this issue with Clipboard.pm be closed now?

**Comment by plicease** [comment]
👍 worked for me just now when I installed it.

**Comment by shlomif** [comment]
@plicease ! Thanks for the update. I'll wait a little for @sshaw . His github account seems active.

**Comment by sshaw** [comment]
Yes working!

**Comment by shlomif** [comment]
> Yes working!

Great, thanks for the head's up! Closing this ticket then.
